version: '3'

services:
    app:
        build:
            context: ./node
        container_name: node-app
        entrypoint: dockerize -wait tcp://db:3306 -timeout 90s node server.js docker-entrypoint.sh
        tty: true
        networks:
            - network-dockerdesafio02
        ports:
            - "3000:3000"
        depends_on:
            - db
            
    db:
        build:
            context: ./mysql
        command: [--innodb-use-native-aio=0,--ignore-db-dir=lost+found]
        container_name: db
        restart: always
        tty: true
        volumes:
            - ./mysql/db:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE=dockerdesafio02
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - network-dockerdesafio02
        ports:
            - "3306:3306"
    nginx:
        build:
            context: ./nginx
        container_name: nginx-reverse
        restart: always
        networks:
            - network-dockerdesafio02        
        ports:
            - "8080:80"
        depends_on:
            - app
       
networks:
    network-dockerdesafio02:
        driver: bridge